let livros = [];
let editingId = null;
const db = window.supabaseClient;
const statusLabel={lendo:'📖 Lendo',lido:'✅ Lido',quero_ler:'📕 Quero ler',pausado:'⏸️ Pausado',abandonado:'❌ Abandonado'};
function esc(value){const div=document.createElement('div');div.textContent=value??'';return div.innerHTML}
function notify(message){const el=document.getElementById('toast');el.textContent=message;el.hidden=false;clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>el.hidden=true,2800)}
function setText(id,value){const el=document.getElementById(id);if(el)el.textContent=value}
async function carregarLivros(){const{data,error}=await db.from('livros').select('*').order('created_at',{ascending:false});if(error)throw error;livros=data||[];renderTudo()}
function atualizarEstatisticas(){const total=livros.length,lendo=livros.filter(l=>l.status==='lendo').length,lidos=livros.filter(l=>l.status==='lido').length,favoritos=livros.filter(l=>l.favorito).length,quero=livros.filter(l=>l.status==='quero_ler').length,pausados=livros.filter(l=>l.status==='pausado').length,paginas=livros.reduce((s,l)=>s+Number(l.pagina_atual||0),0),avaliados=livros.filter(l=>Number(l.avaliacao)>0),media=avaliados.length?(avaliados.reduce((s,l)=>s+Number(l.avaliacao),0)/avaliados.length).toFixed(1):'—';setText('statTotal',total);setText('statLendo',lendo);setText('statLidos',lidos);setText('statFavoritos',favoritos);setText('statPages',paginas);setText('statWant',quero);setText('statPaused',pausados);setText('statRating',media==='—'?'—':`${media} ★`);renderInfografico()}
function renderInfografico(){const box=document.getElementById('statusSummary');if(!box)return;const total=Math.max(livros.length,1);box.innerHTML=`<div class="infographic"><div class="donut" style="--p:${Math.round((livros.filter(l=>l.status==='lido').length/total)*100)}%"><span>${livros.length}</span></div><div class="legend">${Object.entries(statusLabel).map(([key,label])=>{const n=livros.filter(l=>l.status===key).length,p=Math.round(n/total*100);return `<div class="legend-row"><span>${label}</span><strong>${n}</strong><div class="legend-bar"><i style="width:${p}%"></i></div></div>`}).join('')}</div></div>`}
function livroCard(l){const p=l.paginas?Math.min(100,Math.round(Number(l.pagina_atual||0)/Number(l.paginas)*100)):0;const capa=l.capa_url?`<img src="${esc(l.capa_url)}" alt="Capa de ${esc(l.titulo)}" onerror="this.remove()">`:'📖';return `<article class="book-card"><div class="book-card-cover">${capa}</div><div class="book-card-body"><h3>${esc(l.titulo)}</h3><p>${esc(l.autor)}</p><span class="status-pill">${statusLabel[l.status]||esc(l.status)}</span>${l.status==='lendo'?`<p style="margin-top:8px">Progresso: ${p}%</p>`:''}</div></article>`}
function renderDashboard(){const c=document.getElementById('readingNow');if(!c)return;const atuais=livros.filter(l=>l.status==='lendo').slice(0,4);c.innerHTML=atuais.length?atuais.map(livroCard).join(''):'<div class="empty">Nenhum livro em leitura no momento.<br>Que tal começar uma nova jornada?</div>'}
function renderTabela(){const w=document.getElementById('bookTableWrap');if(!w)return;if(!livros.length){w.innerHTML='<div class="empty">📚<br><br>Nenhum livro cadastrado ainda.</div>';return}w.innerHTML=`<table class="book-table"><thead><tr><th>Capa</th><th>Livro</th><th>Gênero</th><th>Status</th><th>Nota</th><th>Ações</th></tr></thead><tbody>${livros.map(l=>`<tr><td>${l.capa_url?`<img class="book-cover-mini" src="${esc(l.capa_url)}" alt="">`:'📖'}</td><td><strong>${esc(l.titulo)}</strong><br><small>${esc(l.autor)}</small></td><td>${esc(l.genero||'—')}</td><td>${statusLabel[l.status]||esc(l.status)}</td><td>${l.avaliacao?'★'.repeat(Number(l.avaliacao)):'—'}</td><td><div class="actions"><button class="icon-btn" onclick="editarLivro(${l.id})" title="Editar">✏️</button><button class="icon-btn delete" onclick="excluirLivro(${l.id})" title="Excluir">🗑️</button></div></td></tr>`).join('')}</tbody></table>`}
function renderTudo(){atualizarEstatisticas();renderDashboard();renderTabela()}
function abrirModal(l=null){editingId=l?.id||null;document.getElementById('modalTitle').textContent=l?'Editar livro':'Adicionar livro';document.getElementById('bookId').value=l?.id||'';document.getElementById('titulo').value=l?.titulo||'';document.getElementById('autor').value=l?.autor||'';document.getElementById('genero').value=l?.genero||'';document.getElementById('anoPublicacao').value=l?.ano_publicacao||'';document.getElementById('capaUrl').value=l?.capa_url||'';document.getElementById('paginas').value=l?.paginas||'';document.getElementById('paginaAtual').value=l?.pagina_atual||0;document.getElementById('status').value=l?.status||'quero_ler';document.getElementById('avaliacao').value=l?.avaliacao||'';document.getElementById('resenha').value=l?.resenha||'';document.getElementById('favorito').value=String(!!l?.favorito);document.getElementById('bookModal').classList.add('show');document.getElementById('titulo').focus()}
function fecharModal(){document.getElementById('bookModal').classList.remove('show');editingId=null}
async function salvarLivro(e){e.preventDefault();const titulo=document.getElementById('titulo').value.trim(),autor=document.getElementById('autor').value.trim();if(!titulo||!autor)return notify('Título e autor são obrigatórios.');const paginas=Number(document.getElementById('paginas').value)||null;let paginaAtual=Number(document.getElementById('paginaAtual').value)||0;if(paginas)paginaAtual=Math.min(Math.max(0,paginaAtual),paginas);const payload={titulo,autor,genero:document.getElementById('genero').value||null,ano_publicacao:Number(document.getElementById('anoPublicacao').value)||null,capa_url:document.getElementById('capaUrl').value.trim()||null,paginas,pagina_atual:paginaAtual,status:document.getElementById('status').value,avaliacao:Number(document.getElementById('avaliacao').value)||null,resenha:document.getElementById('resenha').value.trim()||null,favorito:document.getElementById('favorito').value==='true',updated_at:new Date().toISOString()};const btn=document.getElementById('saveBtn');btn.disabled=true;btn.textContent='Salvando...';try{const r=editingId?await db.from('livros').update(payload).eq('id',editingId):await db.from('livros').insert(payload);if(r.error)throw r.error;fecharModal();notify(editingId?'Livro atualizado!':'Livro adicionado!');await carregarLivros()}catch(error){console.error(error);notify('Não foi possível salvar o livro.')}finally{btn.disabled=false;btn.textContent='Salvar livro'}}
window.editarLivro=id=>{const l=livros.find(x=>x.id===id);if(l)abrirModal(l)};
window.excluirLivro=async id=>{const l=livros.find(x=>x.id===id);if(!l||!confirm(`Excluir “${l.titulo}”? Esta ação não pode ser desfeita.`))return;const{error}=await db.from('livros').delete().eq('id',id);if(error)return notify('Não foi possível excluir o livro.');notify('Livro removido.');await carregarLivros()};
function trocarView(view){document.querySelectorAll('.view').forEach(e=>e.classList.remove('active'));document.getElementById(`view-${view}`)?.classList.add('active');document.querySelectorAll('.side-nav button').forEach(e=>e.classList.toggle('active',e.dataset.view===view));setText('viewTitle',{dashboard:'Dashboard',books:'Biblioteca',stats:'Estatísticas'}[view]||'Dashboard');document.getElementById('sidebar')?.classList.remove('open')}
function configurarSidebar(){const layout=document.querySelector('.admin-layout'),btn=document.getElementById('collapseBtn');if(!layout||!btn)return;const salvo=localStorage.getItem('libraryJashinSidebar')==='collapsed';layout.classList.toggle('sidebar-collapsed',salvo);btn.addEventListener('click',()=>{const c=layout.classList.toggle('sidebar-collapsed');localStorage.setItem('libraryJashinSidebar',c?'collapsed':'expanded');btn.title=c?'Expandir menu':'Recolher menu'})}
document.addEventListener('DOMContentLoaded',async()=>{const session=await window.requireAdmin();if(!session)return;setText('userEmail',session.user.email||'Administrador');configurarSidebar();document.querySelectorAll('.side-nav button').forEach(b=>b.addEventListener('click',()=>trocarView(b.dataset.view)));document.getElementById('logoutBtn')?.addEventListener('click',window.logoutAdmin);document.getElementById('addBookBtn')?.addEventListener('click',()=>abrirModal());document.getElementById('dashboardAddBtn')?.addEventListener('click',()=>abrirModal());document.getElementById('cancelBtn')?.addEventListener('click',fecharModal);document.getElementById('bookForm')?.addEventListener('submit',salvarLivro);document.getElementById('menuBtn')?.addEventListener('click',()=>document.getElementById('sidebar')?.classList.toggle('open'));document.getElementById('bookModal')?.addEventListener('click',e=>{if(e.target.id==='bookModal')fecharModal()});try{await carregarLivros()}catch(error){console.error(error);notify('Não foi possível carregar a biblioteca.')}});