const API_CACHE_KEY='libraryShotenApiCacheV1';
function readCache(){try{return JSON.parse(localStorage.getItem(API_CACHE_KEY)||'{}')}catch{return {}}}
function writeCache(c){try{localStorage.setItem(API_CACHE_KEY,JSON.stringify(c))}catch{}}
function cleanText(v){return String(v||'').replace(/<[^>]*>/g,'').replace(/\s+/g,' ').trim()}
function yearFromDate(v){const m=String(v||'').match(/-?\d{1,4}/);return m?Number(m[0]):null}
function firstAuthor(list){return Array.isArray(list)&&list.length?(typeof list[0]==='string'?list[0]:list[0]?.name):null}
async function fetchJson(url){const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
function normalizeOpenLibrary(i){return{source:'Open Library',sourceKey:'openlibrary',id:i.key||i.edition_key?.[0],title:i.title||'',author:firstAuthor(i.author_name),year:i.first_publish_year??yearFromDate(i.publish_date?.[0]),coverUrl:i.cover_i?`https://covers.openlibrary.org/b/id/${i.cover_i}-L.jpg`:null,genre:Array.isArray(i.subject)?i.subject.find(Boolean):null,description:null,language:Array.isArray(i.language)?i.language[0]:null,isbn:i.isbn?.[0]||null}}
async function searchOpenLibrary(q){const d=await fetchJson(`https://openlibrary.org/search.json?q=${encodeURIComponent(q)}&limit=8&fields=key,title,author_name,first_publish_year,cover_i,subject,language,isbn,publish_date`);return(d.docs||[]).map(normalizeOpenLibrary).filter(x=>x.title)}
function normalizeGoogle(i){const v=i.volumeInfo||{};return{source:'Google Books',sourceKey:'googlebooks',id:i.id,title:v.title||'',author:firstAuthor(v.authors),year:yearFromDate(v.publishedDate),coverUrl:v.imageLinks?.thumbnail?.replace('http://','https://')||v.imageLinks?.smallThumbnail?.replace('http://','https://')||null,genre:v.categories?.[0]||null,description:cleanText(v.description),language:v.language||null,isbn:v.industryIdentifiers?.find(x=>x.type==='ISBN_13')?.identifier||v.industryIdentifiers?.[0]?.identifier||null}}
async function searchGoogleBooks(q){const d=await fetchJson(`https://www.googleapis.com/books/v1/volumes?q=${encodeURIComponent(q)}&maxResults=8&printType=books`);return(d.items||[]).map(normalizeGoogle).filter(x=>x.title)}
function normalizeJikan(i){return{source:'Jikan / MyAnimeList',sourceKey:'jikan',id:i.mal_id,title:i.title||i.title_english||'',author:firstAuthor(i.authors),year:i.published?.from?new Date(i.published.from).getUTCFullYear():i.year||null,coverUrl:i.images?.jpg?.large_image_url||i.images?.jpg?.image_url||null,genre:i.genres?.[0]?.name||i.type||'Mangá',description:cleanText(i.synopsis),language:null,isbn:null}}
async function searchJikan(q){const d=await fetchJson(`https://api.jikan.moe/v4/manga?q=${encodeURIComponent(q)}&limit=8&sfw=true`);return(d.data||[]).map(normalizeJikan).filter(x=>x.title)}
export async function searchBookApis(query,options={}){const term=String(query||'').trim();if(!term)return[];const cache=readCache(),key=`${options.mangaOnly?'manga:':'all:'}${term.toLocaleLowerCase('pt-BR')}`;if(cache[key])return cache[key];const tasks=options.mangaOnly?[searchJikan(term)]:[searchOpenLibrary(term),searchGoogleBooks(term),searchJikan(term)];const settled=await Promise.allSettled(tasks);const results=settled.flatMap(x=>x.status==='fulfilled'?x.value:[]);const seen=new Set();const unique=results.filter(i=>{const k=`${i.title.toLowerCase()}|${(i.author||'').toLowerCase()}|${i.sourceKey}`;if(seen.has(k))return false;seen.add(k);return true}).slice(0,20);cache[key]=unique;writeCache(cache);return unique}
export function formatApiYear(y){if(y===null||y===undefined||y==='')return '';const n=Number(y);return Number.isFinite(n)?(n<0?`${Math.abs(n)} a.C.`:`${n} d.C.`):''}
